# https://hub.docker.com/_/mariadb?tab=description&page=1&ordering=last_updated
# https://docs.docker.com/compose/compose-file/compose-file-v3/
# https://research.sakura.ad.jp/2013/02/14/mariadb-galera-cluster-1/comment-page-1/
services:
  db00:
    build: ./db00
    container_name: db00
    hostname: db00
    init: true
    ports:
      # https://mariadb.com/kb/en/configuring-mariadb-galera-cluster/#network-ports
      # Standard MariaDB Port (default: 3306) 
      - 3306:3306
      # Galera Replication Port (default: 4567) 
      #- 4567:4567
      # IST Port (default: 4568)
      #- 4568:4568
      # SST Port (default: 4444)
      #- 4444:4444
    volumes:
      - type: volume
        source: data_db00
        target: /var/lib/mysql
      #- type: bind
      #  source: ./db00/docker-entrypoint-initdb.d/
      #  target: /docker-entrypoint-initdb.d/
      #- ./db00/docker-entrypoint-initdb.d/galera.sql:/docker-entrypoint-initdb.d/galera.sql:ro
      - ./db00/docker-entrypoint-initdb.d/seed.sql:/docker-entrypoint-initdb.d/seed.sql:ro
      #- ./BACKUP:/BACKUP:ro
    environment:
      - WSREP_NEW_CLUSTER=${WSREP_NEW_CLUSTER:-no}
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=yes
      #- MARIADB_ROOT_HOST=%
      #- MARIADB_ROOT_PASSWORD=secret123
      - MARIADB_DATABASE=demo
      - MARIADB_INITDB_SKIP_TZINFO=true
      - TZ=Asia/Tokyo
    #restart: on-failure
    restart: "no"
    networks:
      db_network:
    #command: ["--wsrep-new-cluster"]

  db01:
    build: ./db00
    container_name: db01
    hostname: db01
    init: true
    ports:
      - 13306:3306
      #- 14567:4567
      #- 14568:4568
      #- 14444:4444
    volumes:
      - type: volume
        source: data_db01
        target: /var/lib/mysql
      - ./db00/docker-entrypoint-initdb.d/galera.sql:/docker-entrypoint-initdb.d/galera.sql:ro
    environment:
      - WSREP_NEW_CLUSTER=${WSREP_NEW_CLUSTER:-no}
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=yes
      #- MARIADB_ROOT_HOST=%
      #- MARIADB_ROOT_PASSWORD=secret123
      - MARIADB_DATABASE=demo
      - MARIADB_INITDB_SKIP_TZINFO=true
      - TZ=Asia/Tokyo
    #restart: on-failure
    restart: "no"
    networks:
      db_network:

  db02:
    build: ./db00
    container_name: db02
    hostname: db02
    init: true
    ports:
      - 23306:3306
      #- 24567:4567
      #- 24568:4568
      #- 24444:4444
    volumes:
      - type: volume
        source: data_db02
        target: /var/lib/mysql
      - ./db00/docker-entrypoint-initdb.d/galera.sql:/docker-entrypoint-initdb.d/galera.sql:ro
    environment:
      - WSREP_NEW_CLUSTER=${WSREP_NEW_CLUSTER:-no}
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=yes
      #- MARIADB_ROOT_HOST=%
      #- MARIADB_ROOT_PASSWORD=secret123
      - MARIADB_DATABASE=demo
      - MARIADB_INITDB_SKIP_TZINFO=true
      - TZ=Asia/Tokyo
    #restart: on-failure
    restart: "no"
    networks:
      db_network:

  db03:
    build: ./db00
    container_name: db03
    hostname: db03
    init: true
    ports:
      - 33306:3306
      #- 34567:4567
      #- 34568:4568
      #- 34444:4444
    volumes:
      - type: volume
        source: data_db03
        target: /var/lib/mysql
      - ./db00/docker-entrypoint-initdb.d/galera.sql:/docker-entrypoint-initdb.d/galera.sql:ro
    environment:
      - WSREP_NEW_CLUSTER=${WSREP_NEW_CLUSTER:-no}
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=yes
      #- MARIADB_ROOT_HOST=%
      #- MARIADB_ROOT_PASSWORD=secret123
      - MARIADB_DATABASE=demo
      - MARIADB_INITDB_SKIP_TZINFO=true
      - TZ=Asia/Tokyo
    #restart: on-failure
    restart: "no"
    networks:
      db_network:


volumes:
  data_db00:
  data_db01:
  data_db02:
  data_db03:

networks:
  db_network:
    driver: bridge
